version: "3.9"

volumes:
  sqlite_data:
  postgresql_data:

services:
  postgresql:
    image: postgres:15.4
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    depends_on:
      - postgresql
    environment:
      - DB_TYPE=postgresql

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
