version: "3.9"

services:
  postgresql:
    image: postgres:15.4
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  mysql:
    image: mysql:8.2
    ports:
      - "3306:3306"
    env_file:
      - ./.env

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - mysql
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend/board
      dockerfile: ../../docker/frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    env_file:
      - ./.env
