version: "3.9"

volumes:
  data:

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    environment:
      - DB_TYPE=sqlite
    volumes:
      - data:/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/board
      dockerfile: ../../docker/frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    env_file:
      - ./.env
    restart: unless-stopped
